package Modelo;
// Generated 22-nov-2016 12:23:04 by Hibernate Tools 4.3.1



/**
 * Configuracion generated by hbm2java
 */
public class Configuracion  implements java.io.Serializable {


     private String nombreTabla;
     private Integer id;

    public Configuracion() {
    }

	
    public Configuracion(String nombreTabla) {
        this.nombreTabla = nombreTabla;
    }
    public Configuracion(String nombreTabla, Integer id) {
       this.nombreTabla = nombreTabla;
       this.id = id;
    }
   
    public String getNombreTabla() {
        return this.nombreTabla;
    }
    
    public void setNombreTabla(String nombreTabla) {
        this.nombreTabla = nombreTabla;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }




}


