package Modelo;
// Generated 22-nov-2016 12:23:04 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Historialtrabajo generated by hbm2java
 */
public class Historialtrabajo  implements java.io.Serializable {


     private HistorialtrabajoId id;
     private Trabajo trabajo;
     private Date fecha;
     private String descripcion;

    public Historialtrabajo() {
    }

	
    public Historialtrabajo(HistorialtrabajoId id, Trabajo trabajo) {
        this.id = id;
        this.trabajo = trabajo;
    }
    public Historialtrabajo(HistorialtrabajoId id, Trabajo trabajo, Date fecha, String descripcion) {
       this.id = id;
       this.trabajo = trabajo;
       this.fecha = fecha;
       this.descripcion = descripcion;
    }
   
    public HistorialtrabajoId getId() {
        return this.id;
    }
    
    public void setId(HistorialtrabajoId id) {
        this.id = id;
    }
    public Trabajo getTrabajo() {
        return this.trabajo;
    }
    
    public void setTrabajo(Trabajo trabajo) {
        this.trabajo = trabajo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


