package Modelo;
// Generated 22-nov-2016 12:23:04 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Listaprecios generated by hbm2java
 */
public class Listaprecios  implements java.io.Serializable {


     private ListapreciosId id;
     private Material material;
     private Date fecha;
     private Integer precio;
     private Integer cantidad;
     
    public Listaprecios() {
    }

	
    public Listaprecios(ListapreciosId id, Material material) {
        this.id = id;
        this.material = material;
    }
    public Listaprecios(ListapreciosId id, Material material, Date fecha, Integer precio, Integer cantidad) {
       this.id = id;
       this.material = material;
       this.fecha = fecha;
       this.precio = precio;
       this.cantidad=cantidad;
    }
   
    public ListapreciosId getId() {
        return this.id;
    }
    
    public void setId(ListapreciosId id) {
        this.id = id;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }

    public Integer getCantidad() {
        return cantidad;
    }

    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


