package Modelo;
// Generated 22-nov-2016 12:23:04 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private int idmaterial;
     private String nombre;
     private String descripcion;
     private Date fechaCompra;
     private Integer cantidad;
     private Integer entrada;
     private Integer salida;
     private Set trabajos = new HashSet(0);
     private Set listaprecioses = new HashSet(0);

    public Material() {
    }

	
    public Material(int idmaterial) {
        this.idmaterial = idmaterial;
    }
    public Material(int idmaterial, String nombre, String descripcion, Date fechaCompra, Integer cantidad, Integer entrada, Integer salida, Set trabajos, Set listaprecioses) {
       this.idmaterial = idmaterial;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechaCompra = fechaCompra;
       this.cantidad = cantidad;
       this.entrada = entrada;
       this.salida = salida;
       this.trabajos = trabajos;
       this.listaprecioses = listaprecioses;
    }
   
    public int getIdmaterial() {
        return this.idmaterial;
    }
    
    public void setIdmaterial(int idmaterial) {
        this.idmaterial = idmaterial;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Integer getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Integer entrada) {
        this.entrada = entrada;
    }
    public Integer getSalida() {
        return this.salida;
    }
    
    public void setSalida(Integer salida) {
        this.salida = salida;
    }
    public Set getTrabajos() {
        return this.trabajos;
    }
    
    public void setTrabajos(Set trabajos) {
        this.trabajos = trabajos;
    }
    public Set getListaprecioses() {
        return this.listaprecioses;
    }
    
    public void setListaprecioses(Set listaprecioses) {
        this.listaprecioses = listaprecioses;
    }

    @Override
    public String toString() {
        return nombre;
    }




}


