package Modelo;
// Generated 22-nov-2016 12:23:04 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Trabajador generated by hbm2java
 */
public class Trabajador  implements java.io.Serializable {


     private Integer idTrabajador;
     private String nombre;
     private String apellido;
     private Integer telefono;
     private String mail;
     private Integer calificacion;
     private Integer estado;
     private Date fechaInicioEstado;
     private Date fechaFinEstado;
     private Set trabajos = new HashSet(0);

    public Trabajador() {
    }

    public Trabajador(String nombre, String apellido, Integer telefono, String mail, Integer calificacion, Integer estado, Date fechaInicioEstado, Date fechaFinEstado, Set trabajos) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.mail = mail;
       this.calificacion = calificacion;
       this.estado = estado;
       this.fechaInicioEstado = fechaInicioEstado;
       this.fechaFinEstado = fechaFinEstado;
       this.trabajos = trabajos;
    }
   
    public Integer getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(Integer idTrabajador) {
        this.idTrabajador = idTrabajador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Date getFechaInicioEstado() {
        return this.fechaInicioEstado;
    }
    
    public void setFechaInicioEstado(Date fechaInicioEstado) {
        this.fechaInicioEstado = fechaInicioEstado;
    }
    public Date getFechaFinEstado() {
        return this.fechaFinEstado;
    }
    
    public void setFechaFinEstado(Date fechaFinEstado) {
        this.fechaFinEstado = fechaFinEstado;
    }
    public Set getTrabajos() {
        return this.trabajos;
    }
    
    public void setTrabajos(Set trabajos) {
        this.trabajos = trabajos;
    }

    @Override
    public String toString() {
        return nombre + ", " + apellido;
    }




}


