package Modelo;
// Generated 22-nov-2016 12:23:04 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Trabajo generated by hbm2java
 */
public class Trabajo  implements java.io.Serializable {


     private int idTrabajo;
     private Trabajador trabajador;
     private Unidad unidad;
     private Integer estado;
     private Date fecha;
     private Integer duracionEstimada;
     private Integer duracionReal;
     private String descripcion;
     private Integer calificacion;
     private Set materials = new HashSet(0);
     private Set historialtrabajos = new HashSet(0);

    public Trabajo() {
    }

	
    public Trabajo(int idTrabajo, Trabajador trabajador, Unidad unidad) {
        this.idTrabajo = idTrabajo;
        this.trabajador = trabajador;
        this.unidad = unidad;
    }
    public Trabajo(int idTrabajo, Trabajador trabajador, Unidad unidad, Integer estado, Date fecha, Integer duracionEstimada, Integer duracionReal, String descripcion, Integer calificacion, Set materials, Set historialtrabajos) {
       this.idTrabajo = idTrabajo;
       this.trabajador = trabajador;
       this.unidad = unidad;
       this.estado = estado;
       this.fecha = fecha;
       this.duracionEstimada = duracionEstimada;
       this.duracionReal = duracionReal;
       this.descripcion = descripcion;
       this.calificacion = calificacion;
       this.materials = materials;
       this.historialtrabajos = historialtrabajos;
    }
   
    public int getIdTrabajo() {
        return this.idTrabajo;
    }
    
    public void setIdTrabajo(int idTrabajo) {
        this.idTrabajo = idTrabajo;
    }
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getDuracionEstimada() {
        return this.duracionEstimada;
    }
    
    public void setDuracionEstimada(Integer duracionEstimada) {
        this.duracionEstimada = duracionEstimada;
    }
    public Integer getDuracionReal() {
        return this.duracionReal;
    }
    
    public void setDuracionReal(Integer duracionReal) {
        this.duracionReal = duracionReal;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    public Set getMaterials() {
        return this.materials;
    }
    
    public void setMaterials(Set materials) {
        this.materials = materials;
    }
    public Set getHistorialtrabajos() {
        return this.historialtrabajos;
    }
    
    public void setHistorialtrabajos(Set historialtrabajos) {
        this.historialtrabajos = historialtrabajos;
    }




}


